[package]
name = "whack.jscript"
version = "1.0.0"
author = "Matheus Dias de Souza <hydroperfox@gmail.com>"
license = "Apache-2.0"
description = ""

[[source]]
path = "src"
include = true

[dependencies]
